/**
 * Vercel 빌드 시 환경변수를 config.js로 주입합니다.
 * Vercel 대시보드 → Settings → Environment Variables 에서 설정:
 *   SUPABASE_URL
 *   SUPABASE_ANON_KEY
 */
const fs = require('fs');
const path = require('path');

const outPath = path.join(__dirname, '..', 'config.js');

const SUPABASE_URL = process.env.SUPABASE_URL || '';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || '';

const payload = {
  SUPABASE_URL,
  SUPABASE_ANON_KEY
};

const content =
  '// Generated by scripts/inject-env.js — do not edit by hand\n' +
  'window.__ENV=' +
  JSON.stringify(payload) +
  ';\n';

fs.writeFileSync(outPath, content, 'utf8');
console.log('config.js written. SUPABASE_URL set:', !!SUPABASE_URL, 'SUPABASE_ANON_KEY set:', !!SUPABASE_ANON_KEY);
